name: Push commit
on:
  schedule:

  - cron: '0 9 9 1 *'

  - cron: '0 9 10 1 *'

  - cron: '0 9 11 1 *'

  - cron: '0 9 12 1 *'

  - cron: '0 9 13 1 *'

  - cron: '0 9 17 1 *'

  - cron: '0 9 25 1 *'

  - cron: '0 9 2 2 *'

  - cron: '0 9 6 2 *'

  - cron: '0 9 7 2 *'

  - cron: '0 9 8 2 *'

  - cron: '0 9 9 2 *'

  - cron: '0 9 10 2 *'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: echo "$(date +'%Y-%m-%d')" >> README.md
      - name: Commit report
        run: |
          git config --global user.name 'samiun06'
          git config --global user.email 'samiun06@users.noreply.github.com'
          git add .
          git commit -m "Automated report"
          git push
