name: Push commit
on:
  schedule:
     - cron:  '0 5 2 6 *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: echo "$(date +'%Y-%m-%d')" >> README.md
      - name: Commit report
        run: |
          git config --global user.name 'Samiun Jahan'
          git config --global user.email 'samiunjahan@users.noreply.github.com'
          git add .
          git commit -am "Automated report"
          git push
