name: Push commit
on:
  schedule:
  - cron: '40 15 2 6 *'
  - cron: '0 9 20 6 *'
  - cron: '0 9 21 6 *'

  - cron: '0 9 22 6 *'

  - cron: '0 9 23 6 *'

  - cron: '0 9 24 6 *'

  - cron: '0 9 28 6 *'

  - cron: '0 9 6 7 *'

  - cron: '0 9 14 7 *'

  - cron: '0 9 18 7 *'

  - cron: '0 9 19 7 *'

  - cron: '0 9 20 7 *'

  - cron: '0 9 21 7 *'

  - cron: '0 9 22 7 *'

  - cron: '0 9 2 8 *'

  - cron: '0 9 3 8 *'

  - cron: '0 9 4 8 *'

  - cron: '0 9 5 8 *'

  - cron: '0 9 8 8 *'

  - cron: '0 9 10 8 *'

  - cron: '0 9 16 8 *'

  - cron: '0 9 17 8 *'

  - cron: '0 9 18 8 *'

  - cron: '0 9 19 8 *'

  - cron: '0 9 29 8 *'

  - cron: '0 9 30 8 *'

  - cron: '0 9 31 8 *'

  - cron: '0 9 1 9 *'

  - cron: '0 9 2 9 *'

  - cron: '0 9 8 9 *'

  - cron: '0 9 14 9 *'

  - cron: '0 9 22 9 *'

  - cron: '0 9 26 9 *'

  - cron: '0 9 27 9 *'

  - cron: '0 9 28 9 *'

  - cron: '0 9 29 9 *'

  - cron: '0 9 30 9 *'

  - cron: '0 9 10 10 *'

  - cron: '0 9 11 10 *'

  - cron: '0 9 12 10 *'

  - cron: '0 9 14 10 *'

  - cron: '0 9 17 10 *'

  - cron: '0 9 19 10 *'

  - cron: '0 9 21 10 *'

  - cron: '0 9 24 10 *'

  - cron: '0 9 26 10 *'

  - cron: '0 9 27 10 *'

  - cron: '0 9 28 10 *'

  - cron: '0 9 7 11 *'

  - cron: '0 9 8 11 *'

  - cron: '0 9 9 11 *'

  - cron: '0 9 10 11 *'

  - cron: '0 9 11 11 *'

  - cron: '0 9 16 11 *'

  - cron: '0 9 21 11 *'

  - cron: '0 9 22 11 *'

  - cron: '0 9 23 11 *'

  - cron: '0 9 24 11 *'

  - cron: '0 9 25 11 *'

  - cron: '0 9 5 12 *'

  - cron: '0 9 9 12 *'

  - cron: '0 9 12 12 *'

  - cron: '0 9 13 12 *'

  - cron: '0 9 14 12 *'

  - cron: '0 9 15 12 *'

  - cron: '0 9 16 12 *'

  - cron: '0 9 19 12 *'

  - cron: '0 9 23 12 *'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: echo "$(date +'%Y-%m-%d')" >> README.md
      - name: Commit report
        run: |
          git config --global user.name 'Samiun Black'
          git config --global user.email 'samiunblack@users.noreply.github.com'
          git add .
          git commit -am "Automated report"
          git push
